"""Local S3 simulator for dry-run mode."""

import os
from typing import Dict, List, Optional
from datetime import datetime


class S3Simulator:
    """Simulates S3 bucket operations without AWS connectivity."""
    
    def __init__(self, bucket_name: str = "simulated-bucket"):
        self.bucket_name = bucket_name
        self.objects: Dict[str, Dict] = {}
        self.access_log: List[Dict] = []
        self.dry_run = os.getenv("DRY_RUN", "1") == "1"
    
    def put_object(self, key: str, metadata: Dict) -> None:
        """Simulate putting an object to S3."""
        self.objects[key] = {
            "key": key,
            "last_modified": datetime.now().isoformat(),
            "metadata": metadata,
            **metadata
        }
    
    def get_object(self, key: str) -> Optional[Dict]:
        """Simulate getting an object from S3."""
        if key in self.objects:
            # Log access
            self.access_log.append({
                "key": key,
                "operation": "GET",
                "timestamp": datetime.now().isoformat()
            })
            return self.objects[key]
        return None
    
    def list_objects(self, prefix: str = "") -> List[Dict]:
        """Simulate listing objects in bucket."""
        if prefix:
            return [obj for key, obj in self.objects.items() if key.startswith(prefix)]
        return list(self.objects.values())
    
    def delete_object(self, key: str) -> bool:
        """Simulate deleting an object."""
        if key in self.objects:
            del self.objects[key]
            return True
        return False
    
    def update_storage_class(self, key: str, storage_class: str) -> bool:
        """Simulate updating object storage class."""
        if key in self.objects:
            self.objects[key]["storage_class"] = storage_class
            self.objects[key]["storage_class_updated"] = datetime.now().isoformat()
            return True
        return False
    
    def get_bucket_metrics(self) -> Dict:
        """Get simulated bucket metrics."""
        total_size_mb = sum(obj.get("size_mb", 0) for obj in self.objects.values())
        
        storage_class_distribution = {}
        for obj in self.objects.values():
            sc = obj.get("storage_class", "STANDARD")
            storage_class_distribution[sc] = storage_class_distribution.get(sc, 0) + 1
        
        return {
            "bucket_name": self.bucket_name,
            "object_count": len(self.objects),
            "total_size_mb": round(total_size_mb, 2),
            "total_size_gb": round(total_size_mb / 1024, 2),
            "storage_class_distribution": storage_class_distribution,
            "access_log_entries": len(self.access_log),
            "dry_run_mode": self.dry_run
        }
    
    def load_objects_from_generator(self, objects: List[Dict]) -> None:
        """Load objects generated by WorkloadGenerator."""
        for obj in objects:
            key = obj["key"]
            self.objects[key] = obj
    
    def load_access_log(self, access_log: List[Dict]) -> None:
        """Load access log from WorkloadGenerator."""
        self.access_log.extend(access_log)
