"""Analysis of the local process-start benchmark (init PROXY - not AWS Lambda).

Same questions as H1 and H2, asked of a real but different measurement: how long
does it take a fresh process to load each runtime + package on one machine?
Tests are labelled H1-proxy / H2-proxy and corrected together (Holm, 4 tests).
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from . import stats  # noqa: E402
from .analysis import COLOURS, RUNTIMES, _jsonable  # noqa: E402


def proxy_label(info: dict) -> str:
    mach = info.get("machine", {})
    where = "GitHub Actions ubuntu-latest runner" if mach.get("github_actions") else mach.get("platform", "local machine")
    return f"local process-start proxy on {where} - NOT an AWS Lambda Init Duration"


def summary(ok: pd.DataFrame, info: dict) -> pd.DataFrame:
    sizes = {(p["runtime"], p["variant"]): p for p in info.get("packages", [])}
    rows = []
    for (r, v), g in ok.groupby(["runtime", "variant"]):
        d = stats.describe(g["init_proxy_ms"])
        pkg = sizes.get((r, v), {})
        rows.append({"runtime": r, "variant": v, "n": d["n"],
                     "init_proxy_p50_ms": d["p50"], "init_proxy_p95_ms": d["p95"], "init_proxy_p99_ms": d["p99"],
                     "handler_p50_ms": float(g["handler_ms"].median()),
                     "process_wall_p50_ms": float(g["process_wall_ms"].median()),
                     "zip_mb": pkg.get("zip_bytes", np.nan) / 1e6, "unzipped_mb": pkg.get("unzipped_bytes", np.nan) / 1e6})
    return pd.DataFrame(rows)


def analyse_proxy(runs: pd.DataFrame, info: dict, fig_dir: str | Path, table_dir: str | Path) -> dict:
    fig_dir, table_dir = Path(fig_dir), Path(table_dir)
    fig_dir.mkdir(parents=True, exist_ok=True)
    table_dir.mkdir(parents=True, exist_ok=True)
    runs = runs.copy()
    for c in ("ok", "warmup"):
        runs[c] = runs[c].astype(str).str.lower().eq("true")
    ok = runs[runs["ok"] & ~runs["warmup"]]
    label = proxy_label(info)
    tests = {}
    opt = ok[ok["variant"] == "optimised"]
    groups = {r: opt.loc[opt["runtime"] == r, "init_proxy_ms"].to_numpy() for r in RUNTIMES if (opt["runtime"] == r).sum() >= 3}
    if len(groups) >= 2:
        tests["H1_proxy"] = stats.compare_many(groups)
    for r in RUNTIMES:
        a = ok.loc[(ok["runtime"] == r) & (ok["variant"] == "default"), "init_proxy_ms"]
        b = ok.loc[(ok["runtime"] == r) & (ok["variant"] == "optimised"), "init_proxy_ms"]
        if len(a) >= 3 and len(b) >= 3:
            tests[f"H2_proxy_{r}"] = stats.compare_two(a, b)
    for k, p in stats.holm({k: t["p"] for k, t in tests.items()}).items():
        tests[k].update(p_holm=p, reject=bool(p < 0.05), family="proxy")
    s = summary(ok, info)
    s.to_csv(table_dir / "proxy_summary.csv", index=False)

    lines = ["<!-- generated by scripts/analyse_proxy.py -->", "", f"**Data: {label}.**", "",
             "| runtime | package | n | init proxy p50 (ms) | p95 | p99 | handler p50 (ms) | zip (MB) | unzipped (MB) |",
             "|---|---|---|---|---|---|---|---|---|"]
    for _, row in s.iterrows():
        lines.append(f"| {row['runtime']} | {row['variant']} | {row['n']} | {row['init_proxy_p50_ms']:.1f} | "
                     f"{row['init_proxy_p95_ms']:.1f} | {row['init_proxy_p99_ms']:.1f} | {row['handler_p50_ms']:.1f} | "
                     f"{row['zip_mb']:.3f} | {row['unzipped_mb']:.3f} |")
    lines += ["", "| test | method | p | p (Holm) | effect | median diff (ms) |", "|---|---|---|---|---|---|"]
    for k, t in tests.items():
        diff = f"{t['median_diff']:.1f}" if "median_diff" in t else "-"
        lines.append(f"| {k} | {t['test']} | {t['p']:.3g} | {t['p_holm']:.3g} | {t['effect_name']} = {t['effect']:.2f} | {diff} |")
    lines += ["", "The proxy has no micro-VM, no code download and no Lambda runtime API. It shows the relative cost",
              "of loading each runtime and package on one machine, not Lambda cold-start times."]
    (table_dir / "proxy_summary.md").write_text("\n".join(lines) + "\n")
    (table_dir / "proxy_tests.json").write_text(json.dumps(_jsonable({"label": label, "tests": tests}), indent=2) + "\n")

    figs = []
    if len(ok):
        fig, ax = plt.subplots(figsize=(7.5, 3.8))
        data, labels, colours = [], [], []
        for r in RUNTIMES:
            for v in ("default", "optimised"):
                x = ok.loc[(ok["runtime"] == r) & (ok["variant"] == v), "init_proxy_ms"]
                if len(x):
                    data.append(x)
                    labels.append(f"{r}\n{v}")
                    colours.append(COLOURS[r])
        bp = ax.boxplot(data, tick_labels=labels, showfliers=False, patch_artist=True)
        for patch, c in zip(bp["boxes"], colours, strict=True):
            patch.set(facecolor=c, alpha=0.35)
        ax.set(yscale="log", ylabel="process start -> handler loaded (ms, log)", title="Init proxy by runtime and package")
        fig.text(0.01, 0.005, label, fontsize=7, color="#555555")
        fig.tight_layout(rect=(0, 0.03, 1, 1))
        fig.savefig(fig_dir / "init_proxy_by_variant.png", dpi=130)
        plt.close(fig)
        figs.append("init_proxy_by_variant.png")
        if s["unzipped_mb"].notna().any():
            fig, ax = plt.subplots(figsize=(5.5, 3.8))
            for _, row in s.iterrows():
                ax.scatter(max(row["unzipped_mb"], 1e-3), row["init_proxy_p50_ms"], color=COLOURS[row["runtime"]], s=40,
                           marker="o" if row["variant"] == "default" else "^")
                ax.annotate(f"{row['runtime']}-{row['variant'][:3]}", (max(row["unzipped_mb"], 1e-3), row["init_proxy_p50_ms"]),
                            fontsize=7, xytext=(4, 3), textcoords="offset points")
            ax.set(xscale="log", yscale="log", xlabel="unzipped package (MB, log)", ylabel="init proxy p50 (ms, log)",
                   title="Package size vs init proxy")
            fig.text(0.01, 0.005, label, fontsize=7, color="#555555")
            fig.tight_layout(rect=(0, 0.03, 1, 1))
            fig.savefig(fig_dir / "package_size_vs_init_proxy.png", dpi=130)
            plt.close(fig)
            figs.append("package_size_vs_init_proxy.png")
    return {"label": label, "tests": tests, "figures": figs}
